# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypemdCli < Formula
  desc "A local-first CLI knowledge management tool"
  homepage "https://typemd.io"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/typemd/typemd/releases/download/v0.2.0/tmd-darwin-x64.tar.gz"
      sha256 "dc2b3364fdc90cbc498a2f84d5fa581c13e78c2bbae148fbd8cbf6cb8cd1a955"

      define_method(:install) do
        bin.install "tmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/typemd/typemd/releases/download/v0.2.0/tmd-darwin-arm64.tar.gz"
      sha256 "b987c1c69d57b2b38d4d91ce71845027f6c8e9f2cbc95f6283d05072643fedb9"

      define_method(:install) do
        bin.install "tmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typemd/typemd/releases/download/v0.2.0/tmd-linux-x64.tar.gz"
      sha256 "af3b97185cacd5fa2f5ddf2c643387a4c1739b97be961fe08387b18847a22b5c"
      define_method(:install) do
        bin.install "tmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typemd/typemd/releases/download/v0.2.0/tmd-linux-arm64.tar.gz"
      sha256 "566f7683d508236dae26eb4a9f93d02cd5ea8477a44a922b1652f4a707bd3440"
      define_method(:install) do
        bin.install "tmd"
      end
    end
  end
end
