# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TypemdCli < Formula
  desc "A local-first CLI knowledge management tool"
  homepage "https://typemd.io"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/typemd/typemd/releases/download/v0.7.0/tmd-darwin-x64.tar.gz"
      sha256 "cb5c7a5302c813dbc9f41252f01ef6c7d702f4210dddbd49c72aca45b742ee44"

      define_method(:install) do
        bin.install "tmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/typemd/typemd/releases/download/v0.7.0/tmd-darwin-arm64.tar.gz"
      sha256 "e0a2a5d28759acfcb05ef75c3fc0f3f4b6efe185c073fa75935444a2d6d6cc08"

      define_method(:install) do
        bin.install "tmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/typemd/typemd/releases/download/v0.7.0/tmd-linux-x64.tar.gz"
      sha256 "bc952572a67a8c41a3e2b324af579cf3235d39b7aa7a5cfce8f0a5dacabf79de"
      define_method(:install) do
        bin.install "tmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/typemd/typemd/releases/download/v0.7.0/tmd-linux-arm64.tar.gz"
      sha256 "7ffb9ce3a6a9edcb777599e0b94ed7982fb6a27171680e4524a98c9d153fa472"
      define_method(:install) do
        bin.install "tmd"
      end
    end
  end
end
